name: MailTape
markdown: kramdown
pygments: true
permalink: /:categories/:title/
timezone: Europe/Paris

## kramdown config to force interpretation into html block
kramdown:
  parse_block_html: true

## prose.io config
prose:
  rooturl: '_posts'
  siteurl: 'http://MailTape.github.io/'
  # relativeLinks: 'http://prose.github.io/starter/links.jsonp'
  media: 'img/'
  metadata:
    _posts:
      - name: "layout"
        field:
          element: "hidden"
          value: "episode"
      - name: "author"
        field:
          element: "multiselect"
          label: "Who are you dude ?"
          placeholder: "Choose your name"
          options:
            - name: "Dimitri"
              value: "dimitri"
            - name: "Julien"
              value: "julien"
            - name: "ImaCrea"
              value: "imacrea"
            - name: "Ludovic"
              value: "ludovic"
      - name: "category"
        field:
          element: "number"
          label: "Which episode ?"
          placeholder: "130"
          type: "number"
      - name: "episode_url"
        field:
          element: "text"
          label: "Episode URL ?"
          placeholder: "http://mailta.pe/129/Valentin-Stip"
          type: "text"
      - name: "episode_FB_Pic"
        field:
          element: "text"
          label: "img FB URL ?"
          placeholder: "http://mailta.pe/img/fbPics_129.jpg"
          type: "text"
      - name: "musicolor"
        field:
          element: "text"
          label: "img musicolor URL ?"
          placeholder: "http://mailta.pe/img/musicolors/129.png"
          type: "text"
      - name: "guest_name"
        field:
          element: "text"
          label: "Guest name ?"
          placeholder: "Valentin Stip"
          type: "text"
      - name: "guest_color"
        field:
          element: "multiselect"
          label: "Color of the artist ?"
          placeholder: "Choose color"
          options:
            - name: "Rough"
              value: "rough"
            - name: "Dreamy"
              value: "dreamy"
            - name: "Vibrant"
              value: "vibrant"
            - name: "Bliss"
              value: "bliss"
            - name: "Trippy"
              value: "trippy"
      - name: "bigTitle_font_ratio"
        field:
          element: "text"
          label: "Big title font ratio ?"
          value: "6"
          type: "text"
      - name: "bigTitle_line_ratio"
        field:
          element: "text"
          label: "Big title line ratio ?"
          value: "1"
          type: "text"
      - name: "guest_pic"
        field:
          element: "text"
          label: "img guest URL"
          placeholder: "img/...jpg"
          type: "text"
      - name: "description"
        field:
          element: "textarea"
          label: "Opengraph description"
          help: "Small text inserted with epiode when shared on fb"
          placeholder: "This morning, welcome on Dream Airlines. Our captain, Valentin Stip, will take us off to glowing masses of condensed sound vapor floating in the sky."
      - name: "track1_link"
        field:
          element: "text"
          label: "Track1 URL ?"
          placeholder: "https://soundcloud.com/otherpeoplerecords/correlation"
          type: "text"
      - name: "track1_color"
        field:
          element: "multiselect"
          label: "Color of the track ?"
          placeholder: "Choose color"
          options:
            - name: "Rough"
              value: "rough"
            - name: "Dreamy"
              value: "dreamy"
            - name: "Vibrant"
              value: "vibrant"
            - name: "Bliss"
              value: "bliss"
            - name: "Trippy"
              value: "trippy"
      - name: "track2_link"
        field:
          element: "text"
          label: "Track2 URL ?"
          placeholder: "https://soundcloud.com/otherpeoplerecords/correlation"
          type: "text"
      - name: "track2_color"
        field:
          element: "multiselect"
          label: "Color of the track ?"
          placeholder: "Choose color"
          options:
            - name: "Rough"
              value: "rough"
            - name: "Dreamy"
              value: "dreamy"
            - name: "Vibrant"
              value: "vibrant"
            - name: "Bliss"
              value: "bliss"
            - name: "Trippy"
              value: "trippy"
      - name: "track3_link"
        field:
          element: "text"
          label: "Track3 URL ?"
          placeholder: "https://soundcloud.com/otherpeoplerecords/correlation"
          type: "text"
      - name: "track3_color"
        field:
          element: "multiselect"
          label: "Color of the track ?"
          placeholder: "Choose color"
          options:
            - name: "Rough"
              value: "rough"
            - name: "Dreamy"
              value: "dreamy"
            - name: "Vibrant"
              value: "vibrant"
            - name: "Bliss"
              value: "bliss"
            - name: "Trippy"
              value: "trippy"
      - name: "track4_link"
        field:
          element: "text"
          label: "Track4 URL ?"
          placeholder: "https://soundcloud.com/otherpeoplerecords/correlation"
          type: "text"
      - name: "track4_color"
        field:
          element: "multiselect"
          label: "Color of the track ?"
          placeholder: "Choose color"
          options:
            - name: "Rough"
              value: "rough"
            - name: "Dreamy"
              value: "dreamy"
            - name: "Vibrant"
              value: "vibrant"
            - name: "Bliss"
              value: "bliss"
            - name: "Trippy"
              value: "trippy"
      - name: "track5_link"
        field:
          element: "text"
          label: "Track5 URL ?"
          placeholder: "https://soundcloud.com/otherpeoplerecords/correlation"
          type: "text"
      - name: "track5_color"
        field:
          element: "multiselect"
          label: "Color of the track ?"
          placeholder: "Choose color"
          options:
            - name: "Rough"
              value: "rough"
            - name: "Dreamy"
              value: "dreamy"
            - name: "Vibrant"
              value: "vibrant"
            - name: "Bliss"
              value: "bliss"
            - name: "Trippy"
              value: "trippy"
      - name: "track6_link"
        field:
          element: "text"
          label: "Track6 URL ?"
          placeholder: "https://soundcloud.com/otherpeoplerecords/correlation"
          type: "text"
      - name: "track6_color"
        field:
          element: "multiselect"
          label: "Color of the track ?"
          placeholder: "Choose color"
          options:
            - name: "Rough"
              value: "rough"
            - name: "Dreamy"
              value: "dreamy"
            - name: "Vibrant"
              value: "vibrant"
            - name: "Bliss"
              value: "bliss"
            - name: "Trippy"
              value: "trippy"
      - name: "track7_link"
        field:
          element: "text"
          label: "Track7 URL ?"
          placeholder: "https://soundcloud.com/otherpeoplerecords/correlation"
          type: "text"
      - name: "track7_color"
        field:
          element: "multiselect"
          label: "Color of the track ?"
          placeholder: "Choose color"
          options:
            - name: "Rough"
              value: "rough"
            - name: "Dreamy"
              value: "dreamy"
            - name: "Vibrant"
              value: "vibrant"
            - name: "Bliss"
              value: "bliss"
            - name: "Trippy"
              value: "trippy"